#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Openbox Pipemenu to change openbox styles

# Dir
Pdir="$HOME/.config/polybar_extra"
Pscript="$Pdir/polybar_extra.sh"

# Variables and functions
MENUS_LIBDIR='/usr/share/archcraft/openbox/menulib'
if ! . "$MENUS_LIBDIR/archcraft.cfg" 2> /dev/null; then
	echo "Error: Failed to locate archcraft.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

# Styles
styles=(`ls -pd --hide={scripts,"*-Bitmap"} $Pdir/*`)
bitmap=(`cd $Pdir && ls *-Bitmap.sh`)

# Generate menu
gen_menu () {
    local count=1
    local bcount=1

	menuStart
	menuSeparator "| Simple |"
	for style in "${styles[@]}"; do
		menuItem "${count}. ${style%.*}" "bash $Pscript $style"
		count=$(($count+1))
	done
if [ ! -f /etc/fonts/conf.d/70-no-bitmaps.conf ] ; then
	menuSeparator "| Bitmap |"
	for bmap in "${bitmap[@]}"; do
		menuItem "${bcount}. ${bmap%-*}" "bash $Pscript $bmap"
		bcount=$(($bcount+1))
	done
fi
	menuEnd
}

{ gen_menu; exit 0; }
