#!/usr/bin/env bash
#### Fix missing files        ########################################################################

if [ ! -s  ~/.config/WM_common_config/which_panel ]
then
	bash ~/.local/bin/fix_missing_file which_panel
fi

if [ ! -s ~/.config/WM_common_config/Rofi_style ] || ( [ "$cat ~/.config/WM_common_config/which_panel" == "polybar" ] && [ ! -s ~/.config/WM_common_config/Polybar_style ] )
then
	bash ~/.local/bin/fix_missing_file style
fi

#### Kill if already running  ########################################################################

for prosses2kill in xfsettingsd picom dunst xfce4-power-manager nm-applet diodon
do
	if [ "$(pidof $prosses2kill)" ]; then
		killall -9 $prosses2kill
	fi
done

#### START SETTINGS  #################################################################################

# Exec first script screenlayout found
if [ "$(ls -A ~/.screenlayout)" ] 
then
	"$(ls ~/.screenlayout/*.sh | head -1)"	
fi
