#!/usr/bin/env bash
#### Fix missing files        ########################################################################

if [ ! -f  ~/.config/WM_common_config/which_panel ]
then
	bash ~/.local/bin/fix_missing_file which_panel
fi

if [ ! "$(cat ~/.config/WM_common_config/Rofi_style 2>/dev/null)" ] || [ ! "$( command -v polybar > /dev/null && cat ~/.config/WM_common_config/Polybar_style 2>/dev/null )" ]
then
	bash ~/.local/bin/fix_missing_file style
fi

#### Kill if already running  ########################################################################

for prosses2kill in xfsettingsd picom dunst xfce4-power-manager nm-applet diodon
do
	if [ "$(pidof $prosses2kill)" ]; then
		killall -9 $prosses2kill
	fi
done

#### START SETTINGS  #################################################################################

# Exec first script screenlayout found
if [ "$(ls -A ~/.screenlayout)" ] 
then
	"$(ls ~/.screenlayout/*.sh | head -1)"	
elif [ "$(ls -A ~/.local/screenlayout)" ]
then
	case "$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | wc -l)" in
		1) ~/.local/screenlayout/singale.sh ;;
		2) ~/.local/screenlayout/multi-monitor.sh ;;
		*) ~/.local/screenlayout/multi-monitor.sh ;;
	esac
else
	~/.local/bin/hub displayselect auto
fi
