#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

WM_common_config="$HOME/.config/WM_common_config"
STYLE="$(cat ${WM_common_config}/Rofi_extra_style)"
rofi_dir="$HOME/.config/rofi_extra"

rofi -no-lazy-grab -show window -theme "$rofi_dir"/"$STYLE"/runner.rasi


rofi \
	-show run \
	-modi run \
	-scroll-method 0 \
	-terminal x-terminal-emulator \
	-theme "/runner.rasi
