#!/bin/bash

sudo apt install -y xmlstarlet xfce4-terminal xfce4-settings light upower qt5ct geany plank i3lock-fancy

sudo apt install -y qt5-style-kvantum 
sudo apt install -y ffmpeg # for screen recoding
sudo apt install -y libnm-dev # for networkmanager_dmenu
sudo apt install -y maim # for ac-shots
sudo apt install -y python2 #for ac-randr ac-kb ac-kb-pipemenu

echo 'deb http://download.opensuse.org/repositories/home:/Head_on_a_Stick:/obmenu-generator/Debian_10/ /' | sudo tee -a /etc/apt/sources.list.d/home:Head_on_a_Stick:obmenu-generator.list
sudo wget -nv https://download.opensuse.org/repositories/home:Head_on_a_Stick:obmenu-generator/Debian_10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install -y obmenu-generator

########################################################################################################################################################################
sudo apt install -y subversion
mkdir -p /tmp/sub
cd /tmp/sub
svn export https://github.com/dari862/arc/trunk/home/
svn export https://github.com/dari862/my-linux-script/trunk/Config/polybar/
svn export https://github.com/dari862/my-linux-script/trunk/Config/rofi/
mv polybar /tmp/sub/home/.config/
mv rofi /tmp/sub/home/.config/
for df in /tmp/sub/home/.config/* ; do
	Directory_File_name=${df##*/}
	[ -d "$HOME/.config/$Directory_File_name" ] && sudo rm -rdf $HOME/.config/$Directory_File_name
	[ -f "$HOME/.config/$Directory_File_name" ] && sudo rm -rdf $HOME/.config/$Directory_File_name
done

mv /tmp/sub/home/.config/* $HOME/.config/
ls -al "/tmp/sub/home/.config" > "$HOME/ls_of_config"
rm -rdf /tmp/sub/home/.config

for df in /tmp/sub/home/.* ; do
	Directory_File_name=${df##*/}
	[ -d "$HOME/.$Directory_File_name" ] && sudo rm -rdf $HOME/.$Directory_File_name
	[ -f "$HOME/.$Directory_File_name" ] && sudo rm -rdf $HOME/.$Directory_File_name
done

########################################################################################################################################################################

mkdir -p  /tmp/openbox_tmp
archcraft_os_stuffs()
{
local url_archcraft_os="$1"
local tempvar="$2"
local openbox_tmp_folder="/tmp/openbox_tmp"
local openbox_folder="/tmp/openbox_now"

git clone $url_archcraft_os $openbox_tmp_folder/openbox_${tempvar}
mkdir -p $openbox_folder/${tempvar}

if [ "$tempvar" != "archcraft" ]
then
	for d in $openbox_tmp_folder/openbox_${tempvar}/* ; do
		[ -d "$d" ] && mv -f ${d}/files/* $openbox_folder/${tempvar}
	done
else
	for d in $openbox_tmp_folder/openbox_${tempvar}/* ; do
		if [ -d "$d" ]
		then
			new_name=${d##*/}
			mv -f ${d}/files $openbox_folder/${tempvar}/${new_name//archcraft-/}
		fi
	done
	mv $openbox_folder/${tempvar}/pixmaps $openbox_folder/${tempvar}/icons
fi
}

archcraft_os_stuffs "https://github.com/archcraft-os/archcraft-themes.git" "themes"

archcraft_os_stuffs "https://github.com/archcraft-os/archcraft-wallpapers.git" "backgrounds"

archcraft_os_stuffs "https://github.com/archcraft-os/archcraft-icons.git" "icons"

archcraft_os_stuffs "https://github.com/archcraft-os/archcraft-cursors.git" "cursors"

archcraft_os_stuffs "https://github.com/archcraft-os/archcraft-packages.git" "archcraft"

git clone https://github.com/archcraft-os/archcraft-openbox.git /tmp/openbox_tmp/archcraft-openbox
git clone https://github.com/firecat53/networkmanager-dmenu.git /tmp/openbox_now/networkmanager-dmenu

mkdir -p /tmp/openbox_tmp/openbox_archcraft/archcraft_about_files
mkdir -p /tmp/openbox_tmp/openbox_archcraft/archcraft_lxdm_files
mv /tmp/openbox_tmp/openbox_archcraft/archcraft-about/* /tmp/openbox_tmp/openbox_archcraft/archcraft_about_files
mv /tmp/openbox_tmp/openbox_archcraft/archcraft-lxdm/* /tmp/openbox_tmp/openbox_archcraft/archcraft_lxdm_files
mv /tmp/openbox_tmp/openbox_archcraft/archcraft_about_files /tmp/openbox_tmp/openbox_archcraft/archcraft-about/files
mv /tmp/openbox_tmp/openbox_archcraft/archcraft_lxdm_files /tmp/openbox_tmp/openbox_archcraft/archcraft-lxdm/files

mkdir -p /tmp/openbox_now/archcraft/openbox
mv /tmp/openbox_tmp/archcraft-openbox/files/icons /tmp/openbox_now/archcraft/openbox/
mv /tmp/openbox_tmp/archcraft-openbox/files/menulib /tmp/openbox_now/archcraft/openbox/
mv /tmp/openbox_tmp/archcraft-openbox/files/pipemenus /tmp/openbox_now/archcraft/openbox/
sed -i 's/menuEnd/menuItem '\''old'\'' "$0 menu.xml"/g' /tmp/openbox_now/archcraft/openbox/pipemenus/ac-ob-menu

for change_content in ac-powermenu ac-change-fonts ac-randr
do
	sed -i 's|.config/openbox/rofi|.config/rofi|g' /tmp/openbox_now/archcraft/openbox/pipemenus/$change_content
	sed -i 's|.config/openbox/rofi|.config/polybar|g' /tmp/openbox_now/archcraft/openbox/pipemenus/$change_content
done

echo "menuEnd" >> /tmp/openbox_now/archcraft/openbox/pipemenus/ac-ob-menu
mv /tmp/openbox_now/archcraft/fonts /tmp/openbox_now/archcraft/archcraft
mv /tmp/openbox_now/cursors/* /tmp/openbox_now/icons/

sudo chown -R root:root /tmp/openbox_now/*

sudo mv /tmp/openbox_now/archcraft /usr/share
sudo mv /tmp/openbox_now/networkmanager-dmenu/networkmanager_dmenu /usr/bin
sudo mv /tmp/openbox_now/networkmanager-dmenu/networkmanager_dmenu.desktop /usr/share/applications/
sudo mv /usr/share/archcraft/archcraft /usr/share/fonts
sudo mv /tmp/openbox_now/icons/* /usr/share/icons
sudo mkdir -p /usr/share/backgrounds
sudo mv /tmp/openbox_now/backgrounds/* /usr/share/backgrounds
for d in /tmp/openbox_now/themes/* ; do
	Directory_name=${d##*/}
	[ -d "/usr/share/themes/$Directory_name" ] && sudo rm -rdf /usr/share/themes/$Directory_name
done
sudo mv /tmp/openbox_now/themes/* /usr/share/themes

mkdir -p /tmp/usr_share_app
wget -P /tmp/usr_share_app https://raw.githubusercontent.com/dari862/arc/main/usr_bin/x-locker
chmod a+x /tmp/usr_share_app/x-locker
cp /usr/share/applications/thunar.desktop /tmp/usr_share_app/x-file-manager.desktop
cp /usr/share/applications/firefox-esr.desktop /tmp/usr_share_app/x-www-browser.desktop
cp /usr/share/applications/terminator.desktop /tmp/usr_share_app/x-terminal-emulator.desktop
cp /usr/share/applications/featherpad.desktop /tmp/usr_share_app/x-text-editor.desktop
sed -i 's/Exec=thunar/Exec=x-file-manager/g' /tmp/usr_share_app/x-file-manager.desktop
sed -i 's/Exec=firefox-esr/Exec=x-www-browser/g' /tmp/usr_share_app/x-www-browser.desktop
sed -i 's/Exec=terminator/Exec=x-terminal-emulator/g' /tmp/usr_share_app/x-terminal-emulator.desktop
sed -i 's/Exec=featherpad/Exec=x-text-editor/g' /tmp/usr_share_app/x-text-editor.desktop
cat << EOF > /tmp/usr_share_app/x-locker.desktop
[Desktop Entry]
Version=1.0
Name=Lock Session
Type=Application
Comment=Locl Session
Terminal=true
Exec=x-locker
Icon=lock
Categories=Power;
GenericName=Lock Session
Keywords=exit;lock
EOF
sudo chown -R root:root /tmp/usr_share_app/*
sudo mv /tmp/usr_share_app/x-locker /usr/bin/
sudo mv /tmp/usr_share_app/*.desktop /usr/share/applications/
