#!/bin/bash

case $1 in
logout)
	DESKTOP_SESSION_all_small_latter=$(echo "$DESKTOP_SESSION" | sed -e 's/\(.*\)/\L\1/')
	if [[ "$DESKTOP_SESSION_all_small_latter" == "openbox" ]]; then
		openbox --exit
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "bspwm" ]]; then
		bspc quit
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "i3" ]]; then
		i3-msg exit
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "qtile" ]]; then	
		qtile cmd-obj -o cmd -f shutdown
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "awesome" ]]; then	
		awesome --replace
	fi
;; 
reload)
	DESKTOP_SESSION_all_small_latter=$(echo "$DESKTOP_SESSION" | sed -e 's/\(.*\)/\L\1/')
	if [[ "$DESKTOP_SESSION_all_small_latter" == "openbox" ]]; then
		openbox --reconfigure
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "bspwm" ]]; then
		bspc --restart
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "i3" ]]; then
		i3-msg restart
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "qtile" ]]; then	
		qtile cmd-obj -o cmd -f restart
	elif [[ "$DESKTOP_SESSION_all_small_latter" == "awesome" ]]; then	
		awesome --replace
	fi
;; 
suspend)
	systemctl suspend
;;
hibernate)
	systemctl hibernate
;;
poweroff)
	systemctl poweroff
;;
reboot)
	systemctl reboot
;;
lock)
	my-locker
;;
esac
