#!/bin/bash

if [ "$1" == "logout" ]
then
	if [[ "$DESKTOP_SESSION" == "Openbox" ]]; then
		openbox --exit
	elif [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
		bspc quit
	elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
		i3-msg exit
	fi
fi 
  
if [ "$1" == "suspend" ]
then
  systemctl suspend
fi
 
if [ "$1" == "hibernate" ]
then
  systemctl hibernate
fi
  
if [ "$1" == "poweroff" ]
then
  systemctl poweroff
fi

if [ "$1" == "lock" ]
then
  my-locker
fi
