#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Openbox Pipemenu to change openbox styles

# Dir
WM_common_config="$HOME/.config/WM_common_config"
P_style_location="${WM_common_config}/Polybar_style"
PEdir="$HOME/.config/polybar_extra"
PEscript="$HOME/local/bin/polybar_extra/polybar_extra.sh"

# Variables and functions
MENUS_LIBDIR='/usr/share/open_stuff/menulib'
if ! . "$MENUS_LIBDIR/archcraft.cfg" 2> /dev/null; then
	echo "Error: Failed to locate archcraft.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

# Styles
styles=(`find $PEdir/* -maxdepth 1 -type d -not -name scripts -not -name "*-Bitmap" -not -name panels -not -name bin`)
bitmap=(`cd $PEdir && ls *-Bitmap`)
panels=(`find $PEdir/panels/* -maxdepth 1 -type f`)

# Generate menu
gen_menu () {
    local count=1
    local bcount=1

	menuStart
	menuSeparator "| Simple |"
	for style in "${styles[@]}"; do
		tmp_style=${style##*/}
		menuItem "${count}. ${tmp_style}" "$PEscript $tmp_style"
		count=$(($count+1))
	done
	if [ ! -f /etc/fonts/conf.d/70-no-bitmaps.conf ] ; then
		menuSeparator "| Bitmap |"
		for bmap in "${bitmap[@]}"; do
			tmp_bmap=${bmap##*/}
			menuItem "${bcount}. ${tmp_bmap}" "$PEscript $tmp_bmap"
			bcount=$(($bcount+1))
		done
	fi
	menuSeparator "| Panels |"
	for panel in "${panels[@]}"; do
		tmp_panel_ini=${panel%".ini"}
		tmp_panel=${tmp_panel_ini##*/}
		menuItem "${count}. ${tmp_panel}" "$PEscript panels/${tmp_panel}"
		count=$(($count+1))
	done
	menuEnd
}

{ gen_menu; exit 0; }
