#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Commands Executed By Openbox Powermenu

## Rofi #############################################
DIR="$HOME/.config/rofi/dialogs"
MSG="Options  -  yes / y / no / n"

cdialog () {
rofi -dmenu\
    -i\
    -no-fixed-num-lines\
    -p "Are You Sure? : "\
    -theme "$DIR"/confirm.rasi
}

## Options #############################################
if  [[ $1 = "--logout" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        my_session_manager logout
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--suspent" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
		mpc -q pause
		amixer set Master mute
		my_session_manager suspend
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
		exit
    else
		rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--reboot" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        my_session_manager reboot
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--shutdown" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        my_session_manager poweroff
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

## Help Menu #############################################
else
echo "
Powermenu For Openbox Menu
Developed By - Aditya Shakya (@adi1090x)

Available options:
--logout	--suspent	--reboot	--shutdown
"
fi
