#!/usr/bin/env bash
## Openbox autostart
## ====================
## When you login to Openbox this autostart script will be executed to set-up your environment 
## and launch any applications you want to run at startup.
## This script is executed by default shell (sh), so 'bashisms' are not supported.
##
## Note: some programs, such as 'nm-applet' are run via XDG autostart.
## To see a list of any XDG autostarted programs run:
## 	/usr/lib/x86_64-linux-gnu/openbox-xdg-autostart --list
## 	/usr/lib/i386-linux-gnu/openbox-xdg-autostart --list
##
## More information about this can be found at: http://openbox.org/wiki/Help:Autostart

#### Kill if already running  ########################################################################

for prosses2kill in xfsettingsd picom dunst ksuperkey xfce4-power-manager nm-applet
do
	if [ "$(pidof $prosses2kill)" ]; then
		killall -9 $prosses2kill
	fi
done

#### START SETTINGS  #################################################################################

# Exec first script screenlayout found
[ -d ~/.screenlayout ] && "$(ls ~/.screenlayout/*.sh | head -1)"	

# Set keyboard settings to 250ms delay and 25cps (characters per second)
xset r rate 250 25	
# Alias for: Super key (win) = Control_Left+Tab
xcape -e "Super_L=Control_L|Tab" 									
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Load xmodmap keys mapping
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap &							

# Touchpad settings
if [ -f /sys/module/battery/initstate ] || [ -d /proc/acpi/battery/BAT0 ]; then
	# Configure touchpad
	synclient VertEdgeScroll=1 HorizEdgeScroll=1 TapButton1=1 2>/dev/null	
	# Disable touchpad while typing
	syndaemon -i .5 -K -t -R -d & 											
fi

#### START APPLICATIONS ###############################################################################
# Set wallpaper
nitrogen --restore &									
# Start compositor
exec picom --config "$HOME/.config/picom.conf" &
# Start Conky
(sleep 2; start_conky.sh) &

if command -v gnome-keyring &> /dev/null
then
	if [ ! `pidof gnome-keyring` ]; then
		# GNOME PolicyKit authentication
		/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
	fi
else
	## polkit agent
	if [ ! `pidof xfce-polkit` ]; then
		/usr/lib/xfce-polkit/xfce-polkit &
	fi
fi

if [ `cat ~/.config/openbox/which_panel | grep "polybar"` ]; then
        if [ "$(grep ~/.config/openbox/rc.xml -e '<file>xfce4-menu.xml</file>' -e '<file>xfce4-menu-color.xml</file>')" ]
        then
			$HOME/.config/My_styles/old.sh
        fi
	# Start polybar
        bash ~/.config/polybar/launch.sh & 
	
	if [ ! "$(pidof plank)" ]; then
		## Launch Plank
        	exec plank &
	fi
fi

if [ `cat ~/.config/openbox/which_panel | grep "xfce4"` ]; then
        if [ ! "$(grep ~/.config/openbox/rc.xml -e '<file>xfce4-menu.xml</file>' -e '<file>xfce4-menu-color.xml</file>')" ]
        then
			$HOME/.config/My_styles/old.sh
        fi
	
	# Start xfce4-panel
        xfce4-panel &
	xfsettingsd &
	
	# Start volume control
	pnmixer &

	# Start network manager
	nm-applet &		

	if [ ! "$(pidof xfce4-clipman)" ]; then
		# Start xfce4-clipman
		xfce4-clipman & 
	fi
fi 

## Enable power management
~/.local/bin/my_power_manager/my_power_managers_session &

if [ -f "~/.config/openbox/welcome" ]
then
	# Show Openbox welcome
	~/.config/openbox/welcome &											
fi
## Notification Daemon
exec dunst &

if [ ! "$(pidof mpd)" ]; then
	## Start Music Player Daemon
	exec mpd &
fi

if [ ! "$(pidof x-file-manager)" ]; then
	## Thunar Daemon
	exec x-file-manager --daemon &
fi
