#!/usr/bin/env bash
## Openbox autostart
## ====================
## When you login to Openbox this autostart script will be executed to set-up your environment 
## and launch any applications you want to run at startup.
## This script is executed by default shell (sh), so 'bashisms' are not supported.
##
## Note: some programs, such as 'nm-applet' are run via XDG autostart.
## To see a list of any XDG autostarted programs run:
## 	/usr/lib/x86_64-linux-gnu/openbox-xdg-autostart --list
## 	/usr/lib/i386-linux-gnu/openbox-xdg-autostart --list
##
## More information about this can be found at: http://openbox.org/wiki/Help:Autostart

#### Kill if already running  ########################################################################

for prosses2kill in xfsettingsd picom polybar dunst ksuperkey xfce4-power-manager
do
	if [[ ! -z "$(pidof $prosses2kill)" ]]; then
		killall -9 $prosses2kill
	fi
done

#### START SETTINGS  #################################################################################
[ -d ~/.screenlayout ] && "$(ls ~/.screenlayout/*.sh | head -1)"	# Exec first script screenlayout found

xset r rate 250 25													# Set keyboard settings to 250ms delay and 25cps (characters per second)
xcape -e "Super_L=Control_L|Tab" 									# Alias for: Super key (win) = Control_Left+Tab
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap &							# Load xmodmap keys mapping

# Touchpad settings
if [ -f /sys/module/battery/initstate ] || [ -d /proc/acpi/battery/BAT0 ]; then
	synclient VertEdgeScroll=1 HorizEdgeScroll=1 TapButton1=1 2>/dev/null	# Configure touchpad
	syndaemon -i .5 -K -t -R -d & 											# Disable touchpad while typing
fi

#### START APPLICATIONS ###############################################################################
# Set wallpaper
nitrogen --restore &									
xfsettingsd &
# Start compositor
exec picom --config "$HOME/.config/picom.conf" &
# Start Conky
(sleep 2; start_conky.sh) &											
# Start volume control
#pnmixer &															
# GNOME PolicyKit authentication
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &	

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

if [ ! -z "$(command -v polybar)" ]
then
        bash ~/.config/polybar/launch.sh &          # Start polybar
	## Launch Plank
	exec plank &
else

        if [ ! "$(grep ~/.config/openbox/rc.xml -e '<file>xfce4-menu.xml</file>')" ]
        then
                ~/.config/openbox/change-2-xfce4
        fi
        xfce4-panel &                           # Start xfce4-panel
        xfce4-clipman &                                   # Start xfce4-clipman           
fi 

## Enable power management
xfce4-power-manager &

# Show Openbox welcome
~/.config/openbox/welcome &											

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Thunar Daemon
exec x-file-manager --daemon &
