#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

if [ "$1" ]
then
	app_2_run_as_root="$1"
else
	WM_common_config="$HOME/.config/WM_common_config"
	STYLE="$(cat ${WM_common_config}/Rofi_style)"
	rofi_dir="$HOME/.config/rofi"
	rofi_command="rofi -theme $rofi_dir/$STYLE/runner.rasi"
	# Apps
	terminal=" Terminal"
	files=" Thunar"
	editor=" Geany"
	clifm=" Ranger"
	lpad=" Leafpad"
	vim=" Vim"
	# Variable passed to rofi
	options="$terminal\n$files\n$editor\n$clifm\n$vim"
	
	# Functions
	chosen="$(echo -e "$options" | $rofi_command -p "Run apps as root" -dmenu -selected-row 0)"
	case $chosen in
    	$terminal)
        	app_2_run_as_root="$(bspterm)"
		Extra_Arg=""
        	;;
    	$files)
        	app_2_run_as_root="$(x-file-manager)"
		Extra_Arg=""
        	;;
    	$editor)
        	app_2_run_as_root="$(geany)"
		Extra_Arg=""
        	;;
    	$clifm)
        	app_2_run_as_root="$(bspterm)"
		Extra_Arg="-e ranger"
        	;;
    	$lpad)
        	app_2_run_as_root="$(x-text-editor)"
		Extra_Arg=""
        	;;
    	$vim)
        	app_2_run_as_root="$(bspterm)"
		Extra_Arg="-e vim"
        	;;
	esac
fi

## rofi sudo askpass helper
export SUDO_ASKPASS="$SCRIPT_DIR"/askpass
	
## execute the application
sudo -A "$app_2_run_as_root" $Extra_Arg
