#!/usr/bin/env bash

rofi_dir="$HOME/.config/rofi"
polybar_dir="$HOME/.config/polybar/scripts/style"
STYLE="$(grep ~/.config/polybar/launch.sh -e STYLE= | cut -d'"' -f 2)"
styles="$(ls -p $polybar_dir | sed "s/.sh/|/g" | tr -d "\n" | sed 's/.$//')"
# Launch Rofi
MENU="$(rofi -no-config -no-lazy-grab -sep "|" -dmenu -i -p '' \
-theme "$rofi_dir"/"$STYLE"/launcher.rasi \
<<< "$styles")"
if [ ! -z "$MENU" ]
then
        $polybar_dir/"$MENU".sh
fi
