#!/usr/bin/env bash

rofi_dir="$HOME/.config/rofi"
polybar_dir="$HOME/.local/bin/polybar/style"
STYLE="$(cat $rofi_dir/style)"
styles_script_dir="$HOME/.local/bin/My_styles"
list_styles="$(ls -p $styles_script_dir | sed "s/.sh/|/g" | tr -d "\n" | sed 's/.$//')"
# Launch Rofi
MENU="$(rofi -no-config -no-lazy-grab -sep "|" -dmenu -i -p '' \
-theme "$rofi_dir"/"$STYLE"/launcher.rasi \
<<< "$list_styles")"
if [ ! -z "$MENU" ]
then
        $styles_script_dir/"$MENU".sh
fi
