#!/bin/sh

ShortName="BAT\nLBC\nTRX\nADA"

if [ ! -d ~/.cache/crypto ]; then
	mkdir ~/.cache/crypto
fi

date > ~/.cache/crypto/price

echo "$ShortName" | while read coin
do
	price=$(curl rate.sx/1$coin 2> /dev/null)
	if [ $coin = "BAT" ]; then
		icon=🦁
	elif [ $coin = "LBC" ]; then
		icon=📖
	elif [ $coin = "TRX" ]; then
		icon=🔺
	elif [ $coin = "ADA" ]; then
		icon="⚛️ "
	fi

	echo "$icon $coin: $price" >> ~/.cache/crypto/price

done
notify-send "Crypto Prices" "$(cat ~/.cache/crypto/price)"
