#!/usr/bin/env bash

rofi_dir="$HOME/.config/rofi"
styles_script_dir="$HOME/.local/bin/My_styles"
default_panel="polybar"
default_style="old"
WM_common_config="$HOME/.config/WM_common_config"
ls_bin="/usr/bin/ls"

mkdir -p "$WM_common_config"

case "$1" in
	which_panel) 
		if [ $(command -v polybar) ] && [ $(command -v xfce4-panel) ]
		then	
			# Launch Rofi
			which_panel_MENU="$(rofi -no-config -no-lazy-grab -sep "|" -dmenu -i -p '' -no-click-to-exit \
			-theme "$rofi_dir"/old/launcher.rasi \
			<<< "polybar|xfce4-panel")"
			if [ ! -z "$which_panel_MENU" ]
			then
				echo "$which_panel_MENU" > ${WM_common_config}/which_panel
        	else
        		echo "$default_panel" > ${WM_common_config}/which_panel
			fi
		else
			if command -v polybar &> /dev/null
			then
				echo "polybar" > ${WM_common_config}/which_panel
			fi
			
			if command -v xfce4-panel &> /dev/null
			then
				echo "xfce4" > ${WM_common_config}/which_panel
			fi
		fi
	;;
	style)
		list_styles="$($ls_bin -p $styles_script_dir | sed "s/.sh/|/g" | tr -d "\n" | sed 's/.$//')"
		# Launch Rofi
		style_MENU="$(rofi -no-config -no-lazy-grab -sep "|" -dmenu -i -p '' -no-click-to-exit \
		-theme "$rofi_dir"/old/launcher.rasi \
		<<< "$list_styles")"
		if [ ! -z "$style_MENU" ]
		then
        		$styles_script_dir/${style_MENU}.sh
        	else
        		$styles_script_dir/${default_style}.sh
		fi
	;;
esac
