#! /bin/bash
# extract range of pages from a PDF
set -euo pipefail
pass=""
check_command() {
  local state=true
  for package in "${@}"; do
    if ! command -v "${package}" >/dev/null; then
      echo "MISSING: ${package} not installed."
      state=false
    fi
  done
  "${state}" && return 0 || return 1
}

! check_command qpdf && exit 3

help(){
	echo "pdfsplit:"
	echo ""
	echo ""
	echo "########"
	echo "pdfsplit (pdf file to split) "
	echo ""
	echo ""
	echo "########"
	echo "pdfsplit (pdf file to split) (range)"
	echo ""
	echo ""
	echo "########"
	echo "pdfsplit (pdf file to split) (range) (-p)"
	exit 0
}

if [ $# -eq 0 ]; then
	help
fi

IN="$(echo $@ | sed 's/.pdf.*/.pdf/' | grep -Eo -e '/[^>]+' || :)"
if [[ -z ${IN} ]]; then
  	echo "ERROR: No input file specified. Exiting."
  	exit 3
elif ! [[ -f "${IN}" ]]; then
  	echo "ERROR: Input ${IN@Q} not found. Exiting."
  	exit 3
fi
OUT="${IN%.*_%d.pdf}"

if [ $# -eq 1 ]; then
	qpdf --split-pages ${IN} ${OUT}
else
	range="$(echo $@ | grep -Eo '[0-9:-]+' || :)"
	if [[ -z ${range} ]]; then
		echo "ERROR: Range is empty. Exiting."
		exit 3
	fi

	check_4_pass="$(echo $@ | grep -o -E ' -p | -P | -password ' || :)"
	
	if [[ ${check_4_pass} ]]; then
		echo -n pass: 
		read -s pass
		if [[ ${pass} ]]; then
			decryption_arg="--password=$pass --decrypt"
		fi
	fi
	qpdf --empty --pages ${decryption_arg} ${IN} ${range} -- ${OUT}
fi
