#!/usr/bin/env bash
set -euo pipefail

opt="${1-h}"

HELP_List=(
"e htop"
"S notify-send  about storage"
"ch notify-send CPU hogs"
"mh notify-send Memory hogs"
"i get_ips"
"E edit script"
)

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
source "$SCRIPT_DIR/config/config.ini"

cp2cb() {
  case "$XDG_SESSION_TYPE" in
    'x11') xclip -r -selection clipboard;;
    'wayland') wl-copy -n;; 
    *) err "Unknown display server";; 
  esac
}

get_ips() {
  declare -A _ips

  _external=$(dig +short myip.opendns.com @resolver1.opendns.com)
  _ips[external]="${_external}"
  
  for _iface in $(ip -4 -o a | awk '{print $2 ":" $4}' | cut -f1 -d"/" ) ; do
    _ips[${_iface%:*}]="${_iface##*:}"   
  done

  selected="$(printf '%s\n' "${!_ips[@]}" | ${rofi_command} -p "ips:" "$@")"
  [ -z "${selected}" ] && exit 1
  echo "${_ips["${selected}"]}" | cp2cb 
  notify-send "IP (in clipboard)" " ${selected}: ${_ips["${selected}"]}"
}

help()
{
	Chosen_OPT="$(printf '%s\n' "${HELP_List[@]}" | ${rofi_command} -p '')"
	opt="$(echo $Chosen_OPT | awk '{ print $1 }')"
	main
}

main()
{
	case $opt in
		e) $TERMINAL -e "htop" & ;;
		m) free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p' ;;
		s) df -h "/" | awk ' /[0-9]/ {print $3 "/" $2}' ;;
		S) notify-send "💽 Disk space" "$(df -h --output=target,used,size 2>/dev/null)" ;;
		ch) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
		mh) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
		i) [[ "${BASH_SOURCE[0]}" == "${0}" ]] && get_ips "$@" ;;
		E) "$TERMINAL" -e "$EDITOR" "$0" ;;	
		*) help ;;
	esac
}
main $opt
