#!/usr/bin/env bash
echo "Updating packages."
sudo sh -c "apt-get update && \
apt-get -y upgrade && \
apt-get -y dist-upgrade && \
apt-get -y autoremove && \
apt-get -y autoclean && \
update-grub"
echo "Packages updated."
