#! /bin/bash
# extract range of pages from a PDF
set -euo pipefail
check_command() {
  local state=true
  for package in "${@}"; do
    if ! command -v "${package}" >/dev/null; then
      echo "MISSING: ${package} not installed."
      state=false
    fi
  done
  "${state}" && return 0 || return 1
}

! check_command qpdf && exit 3

help(){
	echo "pdfsplit options:"
	echo "  -i|--input  <PDF input>"
	echo "  -f|--first  <# of first page to split>"
	echo "  -l|--last   <# of last page to split>"
	echo "  -j|--join   <flag to join split PDF pages together (def: false)"
	exit 0
}

if [ $# -eq 0 ]; then
	help
fi

IN="$(echo $@ | grep -o -E '[0-9:-]+' || :)"
if [[ -z ${IN} ]]; then
  	echo "ERROR: No input file specified. Exiting."
  	exit 3
elif ! [[ -f "${IN}" ]]; then
  	echo "ERROR: Input ${IN@Q} not found. Exiting."
  	exit 3
fi
OUT="${IN%.*_%d.pdf}"

range="$(echo $@ | grep -o -E '[0-9:-]+' || :)"
if [[ -z ${range} ]]; then
  	echo "ERROR: Range is empty. Exiting."
  	exit 3
fi

check_4_pass="$(echo $@ | grep -o -E ' -p | -P | -password ' || :)"
	

if [ $# -eq 1 ]; then
	qpdf --split-pages ${IN} ${OUT}
else
	if [[ ${check_4_pass} ]]; then
		echo -n pass: 
		read -s pass
		echo
	fi
	
	if [[ ${pass} ]]; then
		decryption_arg="--password=$pass --decrypt"
	fi
	qpdf --empty --pages ${decryption_arg} ${IN} ${range} -- ${OUT}
fi
