#!/usr/bin/env bash
check_if_image_is_png()
{
File_type=$(file $1 | awk '{print $2}')
if [ "$File_type" != "PNG" ] 
then
  echo "Type of file you picked is $File_type i3lock only accept PNG" 
  exit 1
fi
}

set_custom_backgrounds_4_i3lock()
{
[ ! -d $i3lock_folder ] && mkdir -p $i3lock_folder
echo "$1" > $i3lock_folder/backgrounds.ini
if [ "$(id -u)" -eq 0 ]
then
  chown -R $user_running_script:$user_running_script $i3lock_folder
fi
}

if [ "$(id -u)" -eq 0 ]
then
  user_running_script=$(logname 2>/dev/null)
  homedir_user_running_script=$( getent passwd "$user_running_script" | cut -d: -f6 )
  i3lock_folder="${homedir_user_running_script}/.config/i3lock"
else
  i3lock_folder="$HOME/.config/i3lock"
fi

if [ "$1" == "-s" ]
then
  if [ ! -z "$2" ]
  then
    check_if_image_is_png $2
    set_custom_backgrounds_4_i3lock $2
    exit 1
  else
    echo "please pick image"
    exit 1
  fi
fi

if [ -f "$i3lock_folder/backgrounds.ini" ]
then
  custom_backgrounds="$(cat ${i3lock_folder}/backgrounds.ini || :)"
fi

if [ -z "$custom_backgrounds" ]
then
  i3lock-fancy
else
  i3lock -i "$custom_backgrounds"
fi
