#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

#### Fix missing files        ########################################################################

if [ ! -f  ~/.local/bin/wm_fixer/which_panel ]
then
	bash ~/.local/bin/wm_fixer/fix_missing_file which_panel
fi

if [ ! "$(cat ~/.config/rofi/style 2>/dev/null)" ] || [ ! "$( command -v polybar > /dev/null && cat ~/.config/polybar/style 2>/dev/null )" ]
then
	bash ~/.local/bin/wm_fixer/fix_missing_file style
fi

#### Kill if already running  ########################################################################

for prosses2kill in xfsettingsd picom dunst xfce4-power-manager nm-applet diodon
do
	if [ "$(pidof $prosses2kill)" ]; then
		killall -9 $prosses2kill
	fi
done

#### START SETTINGS  #################################################################################

# Exec first script screenlayout found
[ -d ~/.screenlayout ] && "$(ls ~/.screenlayout/*.sh | head -1)"	

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' ''
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		let name++
	done
}
workspaces

bspc config border_width        0
bspc config top_padding         50
bspc config right_padding       9
bspc config left_padding        9
bspc config bottom_padding      9
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Alias for: Super key (win) = Control_Left+Tab
xcape -e "Super_L=Control_L|Tab" 									
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout us


#### Window rules ###############################################################################

# remove all rules first
bspc rule -r *:*

# external_rules
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

# 1 > terminal
declare -a terminal=(x-terminal-emulator kitty Alacritty Xfce4-terminal Pcmanfm Thunar)
for i in ${terminal[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

# 2 > web
declare -a web=(firefox chromium Thunderbird TelegramDesktop Hexchat Discord)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3 > code
declare -a code=(Geany code-oss Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > media
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp obs Mplayer2 qBittorrent)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done

# 5 > settings
bspc rule -a 'VirtualBox Manager' desktop='^5' follow=on focus=on
bspc rule -a GParted desktop='^5' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a wine desktop='^5' state=floating follow=on
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off


#### Autostart ###############################################################################

# Lauch xsettingsd daemon
xsettingsd &

if command -v gnome-keyring &> /dev/null
then
	if [ ! `pidof polkit-gnome-authentication-agent-1` ]; then
		# GNOME PolicyKit authentication
		/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
	fi
else
	## polkit agent
	if [ ! `pidof xfce-polkit` ]; then
		/usr/lib/xfce-polkit/xfce-polkit &
	fi
fi

# Lauch keybindings daemon
sxhkd &

#urxvtc
sleep 0.50
urxvtc &

# Restore wallpaper
nitrogen --restore &

## Enable power management
~/.local/bin/my_power_manager/my_power_managers_session &

## Notification Daemon
exec dunst -config ~/.config/bspwm/dunstrc &

if [ ! "$(pidof mpd)" ]; then	
	## Start Music Player Daemon
	exec mpd &
fi

if [ ! "$(pidof x-file-manager)" ]; then
	## Thunar Daemon
	exec x-file-manager --daemon &
fi

if [ ! "$(pidof diodon)" ]; then
	## clipboard manager
	exec diodon &
fi

if [ `cat ~/.local/bin/wm_fixer/which_panel | grep "polybar"` ]; then
        if [ "$(grep ~/.config/openbox/rc.xml -e '<file>xfce4-menu.xml</file>' -e '<file>xfce4-menu-color.xml</file>')" ]
        then
			$HOME/.config/My_styles/old.sh
        fi
	# Start polybar
        bash ~/.config/polybar/launch.sh & 
fi

if [ `cat ~/.local/bin/wm_fixer/which_panel | grep "xfce4"` ]; then
        if [ ! "$(grep ~/.config/openbox/rc.xml -e '<file>xfce4-menu.xml</file>' -e '<file>xfce4-menu-color.xml</file>')" ]
        then
			$HOME/.config/My_styles/old.sh
        fi
	
	# Start xfce4-panel
    xfce4-panel &
	xfsettingsd &
	
	# Start volume control
	pnmixer &

	# Start network manager
	nm-applet &		

	if [ ! "$(pidof xfce4-clipman)" ]; then
		# Start xfce4-clipman
		xfce4-clipman & 
	fi
fi 

# Start compositor
exec picom --config "$HOME/.config/picom.conf" &

# Start bspwm scripts
bspcolors
bspfloat &

#(sleep 2; start_conky.sh) &

## Welcome-App-Run-Once
#archcraft-welcome &
#sed -i -e '/## Welcome-App-Run-Once/Q' "$HOME"/.config/bspwm/bspwmrc
