#! /bin/sh

#Start polybar first
if [ ! -z "$(command -v polybar)" ]
then
        bash ~/.config/polybar/launch.sh &          # Start polybar
else
        xfce4-panel &                           # Start xfce4-panel
        xfce4-clipman &                                                        >
fi 
nitrogen --restore &

# Variable Defines
color0=#3B4252
color4=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

#Fix Mouse curoor on startup 
xsetroot -cursor_name left_ptr

#Set Keyboard Layout
setxkbmap -layout us

#Monitor Config
bspc monitor -d 1 2 3 4 5

#BSPWM Config
bspc config border_width        0
bspc config top_padding         50
bspc config right_padding       9
bspc config left_padding        9
bspc config bottom_padding      9
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.50
bspc config borderless_monocle   true  
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

#Application Rules
bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a wine desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Discord desktop='^2'
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off

#enable touchpad tapping and natural scrolling
#xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
#xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

#Auto-Start
bspc desktop -f ^5
sleep 0.50
urxvtc &
lxpolkit &
picom --config "$HOME/.config/picom.conf" &
#Start xfce4-panel if polybar is not installed
if [ -z "$(command -v polybar)" ]
then
        xfce4-panel &                           # Start xfce4-panel
        xfce4-clipman &                                                        >
fi 
flameshot &
bspc desktop -f ^1
