#!/usr/bin/env bash
set -euo pipefail
# change keyboard layout
# works on any init system
# requirements: dmenu, xorg-setxkbmap

opt="${1-h}"

HELP_List=(
"1 set_kb_layout"
"2 notify-send"
"3 edit script"
"4 echo kb_layout")

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
source "$SCRIPT_DIR/config/config.ini"

if command -v setxkbmap >/dev/null
then
	kb="$(setxkbmap -query | grep -oP 'layout:\s*\K\w+')"
	[ -z "$kb" ] && kb="us"
else
	exit 1
fi

set_kb_layout()
{
	kb_choice="$(awk '/! layout/{flag=1; next} /! variant/{flag=0} flag {print $2, "- " $1}' /usr/share/X11/xkb/rules/base.lst | ${rofi_command} -p "" )"
	kb="$(echo "$kb_choice" | awk '{print $3}')"
	if [ ! -z "$kb" ]
	then
		setxkbmap "$kb"
		pkill -RTMIN+30 "${STATUSBAR:-dwmblocks}"
	fi
}

help()
{
	Chosen_OPT="$(printf '%s\n' "${HELP_List[@]}" | ${rofi_command} -p '')"
	opt="$(echo $Chosen_OPT | awk '{ print $1 }')"
	main
}

main()
{
case $opt in
	1) set_kb_layout ;;
	2) notify-send "⌨  Keyboard/language module" "$(printf "%s" "\- Current layout: $kb")";;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
	4) echo "$kb" ;;
	*) help ;;
esac
}

main $opt


function change_timezone {
  TIMEZONE="UTC"
  res=""

  res="$(timedatectl list-timezones | \
         fzf --layout=reverse \
             --header="Select time zone ('ESC' for default: ${TIMEZONE})" || true)"
  clear

  if [ -n "${res}" ]; then
    TIMEZONE="${res}"
    echo "Using ${TIMEZONE@Q} as time zone."
    sudo timedatectl set-timezone ${TIMEZONE@Q}
  else
    echo "Using default time zone ${TIMEZONE@Q}."
  fi
}

function change_locale {
  local LOCALE="en_US.UTF-8"
  local CHARSET="UTF-8"
  local res
  
  res="$(sed -n "s,^#\?\ \?\([[:alnum:]\.@_\-]\+\)\ \([[:alnum:]\-]\+\)\ *$,\1 \2,p" /etc/locale.gen | \
         fzf --layout=reverse \
             --header="Select locale ('ESC' for default: ${LOCALE})" || true)"
  clear

  if [ -n "${res}" ]; then
    LOCALE="$(echo "${res}" | cut -d" " -f1)"
    CHARSET="$(echo "${res}" | cut -d" " -f2)"
    sed -i "/^#\ \?${LOCALE} ${CHARSET}/s/^#\ \?//" /etc/locale.gen
    locale-gen
    echo "LANG=${LOCALE}" > /etc/locale.conf
    echo "KEYMAP=${LOCALE}" > /etc/vconsole.conf
  else
    show_info "Using default locale ${LOCALE@Q}."
    show_info "Using default charset ${CHARSET@Q}."
  fi
}
