#!/bin/bash

my_power_manager_ini_location="$HOME/.config/my_power_manager/my_power_manager.ini"
get_idletime="$(cat $my_power_manager_ini_location | grep idleAfter= | cut -d '=' -f2)"
get_turnoff_moniter_time="$(cat $my_power_manager_ini_location | grep turnoff_moniter_time= | cut -d '=' -f2)"
get_logout_time="$(cat $my_power_manager_ini_location | grep logout_time= | cut -d '=' -f2)"
get_suspend_time="$(cat $my_power_manager_ini_location | grep suspend_time= | cut -d '=' -f2)"
get_hibernate_time="$(cat $my_power_manager_ini_location | grep hibernate_time= | cut -d '=' -f2)"
get_poweroff_time="$(cat $my_power_manager_ini_location | grep poweroff_time= | cut -d '=' -f2)"
get_brightness_level="$(cat $my_power_manager_ini_location | grep brightness_level= | cut -d '=' -f2)"
get_lock_screen_on_idle="$(cat $my_power_manager_ini_location | grep lock_screen_on_idle= | cut -d '=' -f2)"
################################################

set_idletime="1 idletime"
set_turnoff_moniter_time="2 turnoff_moniter_time"
set_logout_time="3 logout_time"
set_suspend_time="4 suspend_time"
set_hibernate_time="5 hibernate_time"
set_poweroff_time="6 poweroff_time"
set_brightness_level="7 brightness_level"
set_lock_screen_on_idle="8 enable_lock_screen_on_idle"
enable_lock_screen_on_idle="8 enable_lock_screen_on_idle"
disable_lock_screen_on_idle="8 disable_lock_screen_on_idle"
finish="9 finish"
cancel="10 cancel"

################################################

power_manager_MENU=$(yad --title "My Power Manager" --form --field="idle time($get_idletime):NUM" --field="turn off moniter after($get_turnoff_moniter_time):NUM" --field="logout after($get_logout_time):NUM" --field="suspend after($get_suspend_time):NUM" --field="hibernate after($get_hibernate_time):NUM" --field="poweroff after($get_poweroff_time):NUM" --field="set brightness level($get_brightness_level):NUM" --field="lock screen on idle($get_lock_screen_on_idle):CB" "$get_idletime" "$get_turnoff_moniter_time" "$get_turnoff_moniter_time" "$get_logout_time" "$get_suspend_time" "$get_hibernate_time" "$get_brightness_level" 'true!false')

idletime=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $1 }')
turnoff_moniter_time=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $2 }')
logout_time=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $3 }')
suspend_time=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $4 }')
hibernate_time=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $5 }')
poweroff_time=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $6 }')
brightness_level=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $7 }')
lock_screen_on_idle=$(echo $power_manager_MENU | awk 'BEGIN {FS="|" } { print $8 }')
					
if [ ! -z "$idletime" ]
then
  sed -i -e "s|idleAfter=.*|idleAfter=$idletime|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$turnoff_moniter_time" ]
then
  sed -i -e "s|turnoff_moniter_time=.*|turnoff_moniter_time=$turnoff_moniter_time|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$logout_time" ]
then
  sed -i -e "s|logout_time=.*|logout_time=$logout_time|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$suspend_time" ]
then
  sed -i -e "s|suspend_time=.*|suspend_time=$suspend_time|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$hibernate_time" ]
then
  sed -i -e "s|hibernate_time=.*|hibernate_time=$hibernate_time|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$poweroff_time" ]
then
  sed -i -e "s|poweroff_time=.*|poweroff_time=$poweroff_time|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$brightness_level" ]
then
  sed -i -e "s|brightness_level=.*|brightness_level=$brightness_level|g" ~/.config/my_power_manager/my_power_manager.ini
fi

if [ ! -z "$lock_screen_on_idle" ]
then
  sed -i -e "s|lock_screen_on_idle=.*|lock_screen_on_idle=$lock_screen_on_idle|g" ~/.config/my_power_manager/my_power_manager.ini
fi

$HOME/.local/bin/my_power_managers_session


