#!/usr/bin/env bash

for prosses2kill in my_power_manager cbatticon
do
	if [[ ! -z "$(pidof $prosses2kill)" ]]; then
		killall -9 $prosses2kill
	fi
done

$HOME/.local/bin/my_power_manager/my_power_manager &

if [ command -v cbatticon >/dev/null ] && [ -z "$(cat ~/.local/bin/wm_fixer/which_panel | grep 'polybar')" ]
then
	cbatticon -i symbolic -x "bash $HOME/.local/bin/my_power_manager/my_power_manager_gui" &
fi
